# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

[[main]]
  name = "Full Bio"
  url = "#bio"
  weight = 10

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 20

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 30

#[[main]]
#  name = "Recent Projects"
#  url = "#projects"
#  weight = 40

[[main]]
  name = "Clients"
  url = "#clients"
  weight = 50

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

[[main]]
  name = "Certifications"
  url = "#certifications"
  weight = 40

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 50

[[main]]
  name = "Volunteer"
  url = "#volunteer"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "Resume"
  #url = "files/cv.pdf"
  url = "https://www.dropbox.com/s/bfgx7h761kfisdu/Jas%20Sohi%20-%20Resume%20-%20April%202021.pdf?dl=0"
  weight = 70

[[main]]
  name = "Latest Blog Post"
  url = "https://medium.com/@jsohi/whats-in-a-name-an-analysis-of-over-a-century-of-baby-names-a60c6e1a6615"
  weight = 80
