# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

[[main]]
  name = "Bio"
  url = "#bio"
  weight = 10

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 20

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 30

#[[main]]
#  name = "Recent Projects"
#  url = "#projects"
#  weight = 40

[[main]]
  name = "Clients"
  url = "#clients"
  weight = 50

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

[[main]]
  name = "Certifications"
  url = "#certifications"
  weight = 60

[[main]]
  name = "Volunteer"
  url = "#volunteer"
  weight = 60
#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
   name = "Resume"
   #url = "files/cv.pdf"
   url = "https://docs.google.com/document/d/140V8w_9ULxasPt1undqa-iB3GUzr14LRm5vrmcpMCF4/edit#heading=h.8v78y56onko"
   weight = 70
